# Generated by Django 2.2.7 on 2021-09-24 13:39

import common.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user_name', models.CharField(default='columbos', max_length=100, verbose_name='用户名')),
                ('user_pho', models.ImageField(blank=True, null=True, upload_to='user_img/%Y/%m/%d/', verbose_name='文章图片')),
                ('password', models.CharField(default='', max_length=100, verbose_name='用户密码')),
                ('pin_code', models.CharField(default='', max_length=100, verbose_name='Pin码')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='登陆次数')),
                ('token', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='用户token')),
                ('is_merchant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], db_index=True, default='No', max_length=100, verbose_name='是不是商家')),
                ('member_level', models.PositiveIntegerField(default=0, verbose_name='登陆级别')),
                ('user_private_key', models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='私钥')),
                ('user_public_key', models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='公钥')),
                ('factor', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Pin码')),
                ('is_open', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], db_index=True, default='No', max_length=100, verbose_name='是否开启2fa')),
                ('adjust_victor', models.PositiveIntegerField(default=0, verbose_name='调解胜利')),
                ('adjust_fail', models.PositiveIntegerField(default=0, verbose_name='调解失败')),
                ('active_time', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='活跃时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='WalletRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('chain_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='链名称')),
                ('from_addr', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='转出地址')),
                ('to_addr', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='转入地址')),
                ('amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='转账金额')),
                ('tx_fee', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='转账手续费')),
                ('tx_hash', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='交易Hash')),
                ('comment', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='备注')),
                ('w_or_d', models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit'), ('Transfer', 'Transfer')], default='Withdraw', max_length=100, verbose_name='充值提现')),
                ('status', models.CharField(choices=[('Checking', 'Checking'), ('Checked', 'Checked'), ('Trading', 'Trading'), ('SendOut', 'SendOut'), ('Success', 'Success'), ('Fail', 'Fail'), ('CheckPass', 'CheckPass'), ('CheckRefuse', 'CheckRefuse')], default='Checked', max_length=100, verbose_name='状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_record_asset', to='common.Asset', verbose_name='资产')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_record_user', to='clbauth.AuthUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '钱包充值提现记录表',
                'verbose_name_plural': '钱包充值提现记录表',
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('chain_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='链名称')),
                ('address', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='地址')),
                ('balance', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='钱包余额')),
                ('in_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='钱包入账')),
                ('out_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='钱包出账')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet_asset', to='common.Asset', verbose_name='资产')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet_rel', to='clbauth.AuthUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户钱包表',
                'verbose_name_plural': '用户钱包表',
            },
        ),
        migrations.CreateModel(
            name='UserDataStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('order_nums', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='订单数量')),
                ('order_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='订单总计金额')),
                ('in_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='收入总计')),
                ('out_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='支出总计')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stat_asset', to='common.Asset', verbose_name='资产')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_data_stat_rel', to='clbauth.AuthUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户数据统计表',
                'verbose_name_plural': '用户数据统计表',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user_name', models.CharField(blank=True, default='columbos', max_length=100, null=True, verbose_name='用户名')),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='手机号码')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地址')),
                ('is_set', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, verbose_name='是不是默认地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address_rel', to='clbauth.AuthUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收货地址表',
                'verbose_name_plural': '用户收货地址表',
            },
        ),
        migrations.CreateModel(
            name='TansRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='金额')),
                ('trans_way', models.CharField(choices=[('Input', 'Input'), ('Output', 'Output')], default='Input', max_length=100, verbose_name='收入支出')),
                ('source', models.CharField(blank=True, default='', max_length=1280, null=True, verbose_name='支付收入来源')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_relate_record_asset', to='common.Asset', verbose_name='资产')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_relate_record_user', to='clbauth.AuthUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '钱包交易记录表',
                'verbose_name_plural': '钱包交易记录表',
            },
        ),
    ]
