# Generated by Django 2.2.7 on 2022-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clbauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='privkey',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='私钥'),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='pubkey',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='公钥'),
        ),
    ]
