# Generated by Django 2.2.7 on 2021-09-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clbauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('friends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_friends_user', to='clbauth.AuthUser', verbose_name='发送消息的用户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_friends_user', to='clbauth.AuthUser', verbose_name='发送消息的用户')),
            ],
            options={
                'verbose_name': '好友表',
                'verbose_name_plural': '好友表',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('msg_type', models.CharField(blank=True, choices=[('Img', 'Img'), ('Word', 'Word')], default='Word', max_length=100, null=True, verbose_name='消息内容')),
                ('msg_content', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='消息内容')),
                ('msg_img', models.ImageField(blank=True, null=True, upload_to='msg_img/%Y/%m/%d/', verbose_name='聊天图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('recv_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_recv_user', to='clbauth.AuthUser', verbose_name='接收消息用户')),
                ('send_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_send_user', to='clbauth.AuthUser', verbose_name='发送消息的用户')),
            ],
            options={
                'verbose_name': '消息表',
                'verbose_name_plural': '消息表',
            },
        ),
        migrations.CreateModel(
            name='HelpDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='反馈标题')),
                ('content', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='反馈内容')),
                ('top_hd_id', models.PositiveIntegerField(default=0, verbose_name='主题工单')),
                ('process', models.CharField(blank=True, choices=[('UnHandle', 'UnHandle'), ('Handling', 'Handling'), ('Handled', 'Handled')], db_index=True, default='UnHandle', max_length=100, null=True, verbose_name='是否处理')),
                ('admin_user', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('User', 'User')], db_index=True, default='User', max_length=100, null=True, verbose_name='是否处理')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hd_submit_user', to='clbauth.AuthUser', verbose_name='提交工单的用户')),
            ],
            options={
                'verbose_name': '反馈表',
                'verbose_name_plural': '反馈表',
            },
        ),
    ]
