# Generated by Django 2.2.7 on 2021-09-24 13:39

import common.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('clbauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marchant/%Y/%m/%d/', verbose_name='商家LOGO')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='商家名称')),
                ('introduce', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='商家介绍')),
                ('detail', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='商家详细说明')),
                ('goods_num', models.PositiveIntegerField(default=0, verbose_name='商家商品个数')),
                ('settle_percent', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='商家和平台结算比例')),
                ('shop_level', models.PositiveIntegerField(default=0, verbose_name='商家等级')),
                ('shop_score', models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='商家评分')),
                ('month_sell_num', models.PositiveIntegerField(default=0, verbose_name='本月销售量')),
                ('month_sell_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='本月销售金额')),
                ('total_sell_num', models.PositiveIntegerField(default=0, verbose_name='总销售量')),
                ('total_sell_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='总的销售金额')),
                ('adjust_victor', models.PositiveIntegerField(default=0, verbose_name='调解成功次数')),
                ('adjust_fail', models.PositiveIntegerField(default=0, verbose_name='调解失败次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marchant_user_relate', to='clbauth.AuthUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '商家表',
                'verbose_name_plural': '商家表',
            },
        ),
        migrations.CreateModel(
            name='MarchantConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('btc_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='开通商家所需 BTC 个数')),
                ('eth_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='开通商家所需 ETH 个数')),
                ('usdt_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='开通商家所需 USDT 个数')),
                ('config_type', models.CharField(blank=True, choices=[('Marchant', 'Marchant'), ('Other', 'Other')], default='Marchant', max_length=100, null=True, verbose_name='配置类别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '商家配置表',
                'verbose_name_plural': '商家配置表',
            },
        ),
        migrations.CreateModel(
            name='MarchantStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('serice_best', models.PositiveIntegerField(default=0, verbose_name='服务好评')),
                ('service_good', models.PositiveIntegerField(default=0, verbose_name='服务中评')),
                ('service_bad', models.PositiveIntegerField(default=0, verbose_name='服务差评')),
                ('service_avg', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='服务评论星率')),
                ('service_num', models.PositiveIntegerField(default=0, verbose_name='服务星星数量')),
                ('trade_best', models.PositiveIntegerField(default=0, verbose_name='交易好评')),
                ('trade_good', models.PositiveIntegerField(default=0, verbose_name='交易中评')),
                ('trade_bad', models.PositiveIntegerField(default=0, verbose_name='交易差评')),
                ('trade_avg', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='交易评论星率')),
                ('trade_num', models.PositiveIntegerField(default=0, verbose_name='交易星星数量')),
                ('quality_best', models.PositiveIntegerField(default=0, verbose_name='质量好评')),
                ('quality_good', models.PositiveIntegerField(default=0, verbose_name='质量中评')),
                ('quality_bad', models.PositiveIntegerField(default=0, verbose_name='质量差评')),
                ('quality_avg', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='质量评论星率')),
                ('quality_num', models.PositiveIntegerField(default=0, verbose_name='质量评论星星数量')),
                ('total_cmt_num', models.PositiveIntegerField(default=0, verbose_name='总评价星星数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('marchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marchant_data_stat_mct', to='marchant.Marchant', verbose_name='商家')),
            ],
            options={
                'verbose_name': '商家数据统计表',
                'verbose_name_plural': '商家数据统计表',
            },
        ),
        migrations.CreateModel(
            name='MarchantOrderFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('order_id', models.PositiveIntegerField(default=0, verbose_name='订单ID')),
                ('coin_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='币的数量')),
                ('is_valid', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True, verbose_name='是否有效数据')),
                ('is_stat', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True, verbose_name='是否已经统计')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marchant_flow_asset_relate', to='common.Asset', verbose_name='订单')),
                ('marchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marchant_order_flow_relate', to='marchant.Marchant', verbose_name='商家')),
            ],
            options={
                'verbose_name': '商家流水表',
                'verbose_name_plural': '商家流水表',
            },
        ),
        migrations.CreateModel(
            name='MarchantOpenRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('pay_coin_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='支付的币种数量')),
                ('pay_way', models.CharField(blank=True, choices=[('All', 'All'), ('BTC', 'BTC'), ('USDT', 'USDT')], default='BTC', max_length=100, null=True, verbose_name='配置类别')),
                ('pay_at', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='支付时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('marchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marchant_open_marchant', to='marchant.Marchant', verbose_name='收藏的商家')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marchant_open_user_record_relate', to='clbauth.AuthUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '开通商家记录表',
                'verbose_name_plural': '开通商家记录表',
            },
        ),
        migrations.CreateModel(
            name='MarchantCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('marchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marchant_collect_relate', to='marchant.Marchant', verbose_name='收藏的商家')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marchant_collect_user', to='clbauth.AuthUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '商家收藏表',
                'verbose_name_plural': '商家收藏表',
            },
        ),
        migrations.CreateModel(
            name='MarchantBackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('marchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marchant_blacklist_mct_relate', to='marchant.Marchant', verbose_name='黑名单商家')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marchant_blacklist_user', to='clbauth.AuthUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '屏蔽商家表',
                'verbose_name_plural': '屏蔽商家表',
            },
        ),
    ]
