# Generated by Django 2.2.7 on 2021-09-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchantopenrecord',
            name='pay_way',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('ETH', 'ETH'), ('USDT', 'USDT')], default='BTC', max_length=100, null=True, verbose_name='配置类别'),
        ),
    ]
