# Generated by Django 2.2.7 on 2021-09-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clbauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='论坛标题')),
                ('abstract', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='论坛摘要')),
                ('content', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='论坛内容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='论坛查看次数')),
                ('un_likes', models.PositiveIntegerField(default=0, verbose_name='论坛踩次数')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='论坛点赞次数')),
                ('answers', models.PositiveIntegerField(default=0, verbose_name='答案个数')),
                ('is_check', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, verbose_name='是否审核')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '论坛表',
                'verbose_name_plural': '论坛表',
            },
        ),
        migrations.CreateModel(
            name='FormCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='论坛分类名称')),
                ('introduce', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='论坛分类介绍')),
                ('topic_num', models.PositiveIntegerField(default=0, verbose_name='主题数量')),
                ('forum_num', models.PositiveIntegerField(default=0, verbose_name='帖子数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '论坛分类表',
                'verbose_name_plural': '论坛分类表',
            },
        ),
        migrations.CreateModel(
            name='FormTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='论坛主题名称')),
                ('introduce', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='论坛主题介绍')),
                ('topic_num', models.PositiveIntegerField(default=1, verbose_name='主题数量')),
                ('forum_num', models.PositiveIntegerField(default=0, verbose_name='帖子数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_cat_topic', to='forum.FormCat', verbose_name='论坛分类')),
            ],
            options={
                'verbose_name': '论坛主题表',
                'verbose_name_plural': '论坛主题表',
            },
        ),
        migrations.CreateModel(
            name='FormCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='论坛内容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='论坛查看次数')),
                ('un_likes', models.PositiveIntegerField(default=0, verbose_name='论坛踩次数')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='论坛点赞次数')),
                ('answers', models.PositiveIntegerField(default=0, verbose_name='答案个数')),
                ('is_check', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, verbose_name='是否审核')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('father_forum_cy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.FormCommentReply', verbose_name='父论坛')),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_comment_reply', to='forum.Form', verbose_name='论坛类别')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_comment_reply_user', to='clbauth.AuthUser', verbose_name='论坛发布者')),
            ],
            options={
                'verbose_name': '论坛评论回复表',
                'verbose_name_plural': '论坛评论回复表',
            },
        ),
        migrations.AddField(
            model_name='form',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_cat', to='forum.FormCat', verbose_name='论坛类别'),
        ),
        migrations.AddField(
            model_name='form',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_topic', to='forum.FormTopic', verbose_name='论坛主题'),
        ),
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_pulish_user', to='clbauth.AuthUser', verbose_name='论坛发布者'),
        ),
    ]
