# Generated by Django 2.2.7 on 2021-09-24 13:39

import common.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('marchant', '0001_initial'),
        ('clbauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(default='', max_length=512, verbose_name='商品标题')),
                ('goods_type', models.CharField(default='实体商品', max_length=100, verbose_name='商品类别')),
                ('name', models.CharField(default='', max_length=512, verbose_name='商品名称')),
                ('detail', models.CharField(default='', max_length=512, verbose_name='商品介绍')),
                ('mark', models.CharField(default='', max_length=512, verbose_name='商品备注')),
                ('serveice', models.CharField(default='', max_length=512, verbose_name='服务说明')),
                ('calc_way', models.CharField(choices=[('件', '件'), ('个', '个'), ('斤', '斤')], default='件', max_length=100, verbose_name='计量方式')),
                ('pay_way', models.CharField(choices=[('All', 'All'), ('BTC', 'BTC'), ('USDT', 'USDT')], default='All', max_length=100, verbose_name='支持支付的方式')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='商品总量')),
                ('left_amount', models.PositiveIntegerField(default=100000, verbose_name='商品剩余量')),
                ('sell_nums', models.PositiveIntegerField(default=0, verbose_name='商品卖出量')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='商品浏览次数')),
                ('return_goods_pc', models.CharField(default='', max_length=1024, verbose_name='退换货政策')),
                ('price', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='商品价格')),
                ('is_sale', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100, verbose_name='商品上下架')),
                ('is_admin', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100, verbose_name='商品是否代管')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
            },
        ),
        migrations.CreateModel(
            name='GoodsAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('key', models.CharField(default='', max_length=100, verbose_name='属性Key')),
                ('value', models.CharField(default='', max_length=100, verbose_name='属性值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '商品属性表',
                'verbose_name_plural': '商品属性表',
            },
        ),
        migrations.CreateModel(
            name='GoodsCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='分类名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '商品分类表',
                'verbose_name_plural': '商品分类表',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_img/%Y/%m/%d/', verbose_name='商品图片')),
                ('mark', models.CharField(default='', max_length=100, verbose_name='图标备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '商品图片表',
                'verbose_name_plural': '商品图片表',
            },
        ),
        migrations.CreateModel(
            name='GoodsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('NO_PAY', 'NO_PAY'), ('PAY_SUCCESS', 'PAY_SUCCESS'), ('PAY_FAIL', 'PAY_FAIL'), ('SEND_GOODS', 'SEND_GOODS'), ('RECV_GOODS', 'RECV_GOODS'), ('RETURN_GOODS', 'RETURN_GOODS'), ('FINISH', 'FINISH'), ('PAYWAYUSDT', 'PAYWAYUSDT'), ('PAYWAYBTC', 'PAYWAYBTC')], default='Unpay', max_length=100, verbose_name='订单状态')),
                ('goods_name', models.CharField(default='', max_length=512, verbose_name='商品名称')),
                ('cny_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='总支付的人民币')),
                ('goods_price', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='商品价格')),
                ('asset_cny_price', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='支付时币种的人民币价格')),
                ('goods_detail', models.CharField(default='', max_length=512, verbose_name='商品介绍')),
                ('buy_nums', models.PositiveIntegerField(default=1, verbose_name='购买数量')),
                ('pay_way', models.CharField(choices=[('All', 'All'), ('BTC', 'BTC'), ('USDT', 'USDT')], default='件', max_length=100, verbose_name='计量方式')),
                ('pay_asset_cny_price', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='支付时资产的人民币价格')),
                ('pay_coin_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='支付的币的数量')),
                ('order_number', models.CharField(default='', max_length=512, verbose_name='订单号')),
                ('logistics', models.CharField(default='', max_length=512, verbose_name='物流公司')),
                ('express_number', models.CharField(default='', max_length=512, verbose_name='快递运单号')),
                ('ret_logistics', models.CharField(default='', max_length=512, verbose_name='退货物流公司')),
                ('ret_ship_number', models.CharField(default='', max_length=512, verbose_name='退货运单号')),
                ('failure_reason', models.CharField(default='', max_length=512, verbose_name='失败原因')),
                ('pay_at', models.CharField(default='', max_length=512, verbose_name='支付时间')),
                ('deal_at', models.CharField(default='', max_length=512, verbose_name='处理时间')),
                ('is_cancle', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, verbose_name='是否退换货')),
                ('is_comment', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, verbose_name='是否评价价')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_order_relate', to='goods.Goods', verbose_name='商品')),
                ('goods_atrr', models.ManyToManyField(blank=True, null=True, to='goods.GoodsAttr', verbose_name='商品属性')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_order_logo_image', to='goods.GoodsImage', verbose_name='商品LOGO')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marchant_goods_order_relate', to='marchant.Marchant', verbose_name='商家')),
                ('pay_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Asset', verbose_name='支付币种')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_goods_user', to='clbauth.AuthUser', verbose_name='购买商品的人')),
                ('user_address', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recive_goods_address_relate', to='clbauth.UserAddress', verbose_name='收货地址')),
            ],
            options={
                'verbose_name': '商品订单表',
                'verbose_name_plural': '商品订单表',
            },
        ),
        migrations.CreateModel(
            name='GoodsSate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('state', models.CharField(default='中国', max_length=100, verbose_name='产地名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '商品产地表',
                'verbose_name_plural': '商品产地表',
            },
        ),
        migrations.CreateModel(
            name='OrederReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ret_goods_rs', models.CharField(default='', max_length=512, verbose_name='退货原因')),
                ('ret_pay_rs', models.CharField(default='', max_length=512, verbose_name='商家拒绝原因')),
                ('qs_describe', models.CharField(default='', max_length=512, verbose_name='问题描述')),
                ('qs_img_one', models.ImageField(blank=True, null=True, upload_to='order/%Y/%m/%d/', verbose_name='问题图片1')),
                ('qs_img_two', models.ImageField(blank=True, null=True, upload_to='order/%Y/%m/%d/', verbose_name='问题图片2')),
                ('qs_img_three', models.ImageField(blank=True, null=True, upload_to='order/%Y/%m/%d/', verbose_name='问题图片3')),
                ('adjust_content', models.CharField(default='', max_length=5120, verbose_name='申述描述')),
                ('adjust_reason', models.CharField(default='', max_length=5120, verbose_name='申述描述')),
                ('vectory_id', models.PositiveIntegerField(default=1, verbose_name='申诉胜出方')),
                ('fail_id', models.PositiveIntegerField(default=1, verbose_name='申诉失败方')),
                ('process', models.CharField(choices=[('RETURN_GOODS', 'RETURN_GOODS'), ('CANCLE_RETURN_GOODS', 'CANCLE_RETURN_GOODS'), ('RETURN_SELLER_RJT', 'RETURN_SELLER_RJT'), ('RETURN_SELLER_ACPT', 'RETURN_SELLER_ACPT'), ('BUYER_APPOVAL', 'BUYER_APPOVAL'), ('APPOVAL_FAIL', 'APPOVAL_FAIL'), ('APPOVAL_SUCCESS', 'APPOVAL_SUCCESS'), ('BUYER_SEND_GOODS', 'BUYER_SEND_GOODS'), ('BUYER_RECV_GOODS', 'BUYER_RECV_GOODS'), ('SELLER_RECV_GOODS', 'SELLER_RECV_GOODS'), ('SELLER_SEND_GOODS', 'SELLER_SEND_GOODS'), ('SELLER_RETURN_MNY', 'SELLER_RETURN_MNY')], default='RETURN_GOODS', max_length=100, verbose_name='订单状态')),
                ('ret_order_status', models.CharField(default='', max_length=100, verbose_name='退换货前订单状态')),
                ('is_send_goods', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, verbose_name='是否已发货物')),
                ('fund_ret', models.CharField(choices=[('Return', 'Return'), ('Exchange', 'Exchange')], default='Return', max_length=100, verbose_name='退货换货')),
                ('left_time', models.CharField(default='', max_length=512, verbose_name='剩余处理时长')),
                ('deal_time', models.CharField(default='', max_length=512, verbose_name='处理时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_order_return', to='goods.GoodsOrder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单退货流程表',
                'verbose_name_plural': '订单退货流程表',
            },
        ),
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('quality_star', models.PositiveIntegerField(default=0, verbose_name='评论的质量星级')),
                ('service_star', models.PositiveIntegerField(default=0, verbose_name='服务评论星级')),
                ('trade_star', models.PositiveIntegerField(default=0, verbose_name='交易评论星级')),
                ('content', models.CharField(default='', max_length=512, verbose_name='评论内容')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_relate_comment', to='goods.Goods', verbose_name='商品')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_marchant_comment', to='marchant.Marchant', verbose_name='所属商家')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_comment_user', to='clbauth.AuthUser', verbose_name='评论人')),
            ],
            options={
                'verbose_name': '商品评价表',
                'verbose_name_plural': '商品评价表',
            },
        ),
        migrations.CreateModel(
            name='GoodsCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_collect_db', to='goods.Goods', verbose_name='收藏的商品')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_collect_user', to='clbauth.AuthUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品收藏表',
                'verbose_name_plural': '商品收藏表',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_atrr',
            field=models.ManyToManyField(blank=True, null=True, to='goods.GoodsAttr', verbose_name='商品属性'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_cat', to='goods.GoodsCat', verbose_name='商品分类'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_image',
            field=models.ManyToManyField(blank=True, null=True, to='goods.GoodsImage', verbose_name='商品图片'),
        ),
        migrations.AddField(
            model_name='goods',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_logo_image', to='goods.GoodsImage', verbose_name='商品LOGO'),
        ),
        migrations.AddField(
            model_name='goods',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marchant_goods_relate', to='marchant.Marchant', verbose_name='商家'),
        ),
        migrations.AddField(
            model_name='goods',
            name='origin_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_origin_state', to='goods.GoodsSate', verbose_name='商品产地'),
        ),
    ]
